version: '3'

services:
  app:
    build: 
      context: ./
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db 
  db:
    image: postgres:14.2
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - '5432:5432'
    networks: 
      - node-network   

networks: 
  node-network:
    driver: bridge  